# Generated by Django 3.1.2 on 2020-11-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
